// PLEASE USE YOUR OWN MAPBOX API KEY. API KEY IS FOR DEMO PURPOSES ONLY.
window.MAPBOX_CRED =
  "pk.eyJ1IjoibmthZGF3ZWQiLCJhIjoiY21hMm5tbXVqMGxodzJqcHl1OXFhYmNxZyJ9.EGl7jkko2FxV0uN6PhUXcQ";

// PLEASE USE YOUR OWN API KEY. API KEY IS FOR DEMO PURPOSES ONLY. https://shademap.app/about
window.SHADEMAP_CRED =
  "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5hZHVsYWthZGF3ZWRkdXdhQGdtYWlsLmNvbSIsImNyZWF0ZWQiOjE3NDUzMzEyMjUxOTksImlhdCI6MTc0NTMzMTIyNX0.RAJ-qHAKLvC3v9gb-5RMIXp2BdrqfsmcxfElBHIb_S0";